version: "3.9"

services:
  app:
    build: .
    container_name: server-app
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:7.0
    container_name: mongodb-alarms
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongodb:/data/db

volumes:
  mongodb-data:
    driver: local
